#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
class TinyCC < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    48,    61,    48,    19,     6,    10,    95,    69,    70,    20,
    48,    60,    53,    51,    23,    51,    29,    48,    40,    32,
    40,    33,    34,    51,    50,     5,    50,    18,    40,    48,
    51,    23,    62,    29,    50,    40,    32,    14,    33,    34,
    10,    50,    51,    23,    48,    29,    48,    40,    32,    98,
    33,    34,    61,    50,    48,    99,    48,    51,    48,    51,
    63,    64,    40,    23,    40,    18,    48,    51,    50,    51,
    50,    51,    74,    48,    40,    48,    74,    25,    50,    51,
    50,    97,    50,    48,    74,    10,    51,    53,    51,    54,
    50,    74,    96,    74,    55,    48,    51,    50,    53,    50,
    59,    74,    48,    12,    13,    48,    62,    50,    51,    23,
    25,    29,    48,    40,    32,    51,    33,    34,    51,    50,
    74,    48,    11,    40,    10,    51,    50,   103,    48,    50,
    74,    71,    72,     5,    51,    48,    50,   nil,    48,    40,
    57,    51,    23,   nil,    29,    50,    40,    32,    51,    33,
    34,    51,    50,    74,    48,    48,    40,    48,    48,    50,
    71,    72,    50,    65,    66,    67,    68,    51,    51,   nil,
    51,    51,    74,    74,   nil,    74,    74,   nil,    50,    50,
   nil,    50,    50,    65,    66,    67,    68,    65,    66,    67,
    68,    79,    53,    52,    53,    69,    70,    69,    70,    69,
    70,    69,    70,    71,    72,    63,    64 ]

racc_action_check = [
   103,    40,    55,    16,     1,    13,    75,    90,    90,    16,
    99,    40,    75,   103,   103,    55,   103,    97,   103,   103,
    55,   103,   103,    99,   103,     1,    55,    14,    99,    96,
    97,    97,    80,    97,    99,    97,    97,     9,    97,    97,
    18,    97,    96,    96,    54,    96,    53,    96,    96,    82,
    96,    96,    74,    96,    59,    82,    51,    54,    48,    53,
    42,    42,    54,    19,    53,    20,    72,    59,    54,    51,
    53,    48,    59,    71,    51,    70,    48,    23,    59,    72,
    51,    78,    48,    69,    72,    25,    71,    78,    70,    32,
    72,    71,    77,    70,    33,    26,    69,    71,    77,    70,
    39,    69,    68,     8,     8,    61,    41,    69,    26,    26,
    26,    26,    66,    26,    26,    68,    26,    26,    61,    26,
    68,    34,     6,    61,     5,    66,    68,   100,    35,    61,
    66,    92,    92,     0,    34,    65,    66,   nil,    60,    34,
    35,    35,    35,   nil,    35,    34,    35,    35,    65,    35,
    35,    60,    35,    65,    64,    63,    60,    62,    67,    65,
    91,    91,    60,    43,    43,    43,    43,    64,    63,   nil,
    62,    67,    64,    63,   nil,    62,    67,   nil,    64,    63,
   nil,    62,    67,    85,    85,    85,    85,    86,    86,    86,
    86,    56,    56,    30,    30,    89,    89,    88,    88,    87,
    87,    44,    44,    45,    45,    84,    84 ]

racc_action_pointer = [
   112,     4,   nil,   nil,   nil,   100,   122,   nil,    81,    18,
   nil,   nil,   nil,   -19,     6,   nil,   -14,   nil,    16,    43,
    44,   nil,   nil,    56,   nil,    61,    89,   nil,   nil,   nil,
   171,   nil,    70,    75,   115,   122,   nil,   nil,   nil,    84,
   -18,    91,    49,   156,   196,   201,   nil,   nil,    52,   nil,
   nil,    50,   nil,    40,    38,    -4,   169,   nil,   nil,    48,
   132,    99,   151,   149,   148,   129,   106,   152,    96,    77,
    69,    67,    60,   nil,    33,   -11,   nil,    75,    64,   nil,
    17,   nil,    32,   nil,   194,   176,   180,   194,   192,   190,
     2,   158,   129,   nil,   nil,   nil,    23,    11,   nil,     4,
   101,   nil,   nil,    -6,   nil ]

racc_action_default = [
   -60,   -60,    -1,    -3,    -4,   -60,   -60,    -2,   -60,    -6,
    -8,   105,    -5,   -60,   -12,    -7,   -60,   -10,   -60,   -60,
   -60,   -13,    -9,   -24,   -11,   -60,   -27,   -22,    -6,   -14,
   -60,   -16,   -60,   -60,   -60,   -60,   -23,   -25,   -28,   -30,
   -54,   -32,   -34,   -36,   -39,   -44,   -47,   -50,   -60,   -52,
   -55,   -60,   -15,   -60,   -60,   -60,   -60,   -21,   -26,   -60,
   -60,   -59,   -60,   -60,   -60,   -60,   -60,   -60,   -60,   -60,
   -60,   -60,   -60,   -51,   -54,   -60,   -29,   -60,   -60,   -20,
   -33,   -31,   -60,   -57,   -35,   -37,   -38,   -40,   -41,   -42,
   -43,   -45,   -46,   -48,   -49,   -56,   -60,   -60,   -53,   -60,
   -17,   -19,   -58,   -60,   -18 ]

racc_goto_table = [
    37,    73,    56,    76,    26,    27,    17,     9,    36,    58,
    81,    83,    24,    91,    92,    15,    85,    86,    80,    75,
    21,    84,    77,    78,    93,    94,    35,    28,    87,    88,
    89,    90,     2,     7,    22,    16,     1,    82,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   102,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   100,   101,   nil,   nil,   nil,   nil,   nil,   104 ]

racc_goto_check = [
    10,    21,    11,    14,    12,     3,     9,     6,     3,    10,
    14,    14,     9,    20,    20,     6,    18,    18,    16,    11,
     6,    17,    11,    11,    21,    21,    13,     6,    19,    19,
    19,    19,     2,     2,     8,     7,     1,    24,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    10,    10,   nil,   nil,   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,    36,    32,   -18,   nil,   nil,     2,    21,    15,    -8,
   -26,   -32,   -19,     0,   -50,   nil,   -41,   -41,   -47,   -37,
   -56,   -47,   nil,   nil,   -24 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     8,   nil,   nil,    31,   nil,
   nil,    30,   nil,   nil,    38,    39,    41,    42,    43,    44,
    45,    46,    47,    49,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 32, :_reduce_none,
  2, 32, :_reduce_none,
  1, 33, :_reduce_none,
  1, 33, :_reduce_none,
  3, 34, :_reduce_none,
  1, 36, :_reduce_none,
  3, 36, :_reduce_none,
  1, 37, :_reduce_none,
  6, 35, :_reduce_none,
  1, 38, :_reduce_none,
  3, 38, :_reduce_none,
  0, 38, :_reduce_none,
  2, 40, :_reduce_none,
  1, 41, :_reduce_none,
  2, 41, :_reduce_none,
  1, 41, :_reduce_none,
  5, 41, :_reduce_none,
  7, 41, :_reduce_none,
  5, 41, :_reduce_none,
  3, 41, :_reduce_none,
  4, 39, :_reduce_none,
  1, 43, :_reduce_none,
  2, 43, :_reduce_none,
  0, 43, :_reduce_none,
  1, 44, :_reduce_none,
  2, 44, :_reduce_none,
  0, 44, :_reduce_none,
  1, 42, :_reduce_none,
  3, 42, :_reduce_none,
  1, 45, :_reduce_none,
  3, 45, :_reduce_none,
  1, 46, :_reduce_none,
  3, 46, :_reduce_none,
  1, 47, :_reduce_none,
  3, 47, :_reduce_none,
  1, 48, :_reduce_none,
  3, 48, :_reduce_none,
  3, 48, :_reduce_none,
  1, 49, :_reduce_none,
  3, 49, :_reduce_none,
  3, 49, :_reduce_none,
  3, 49, :_reduce_none,
  3, 49, :_reduce_none,
  1, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  1, 51, :_reduce_none,
  3, 51, :_reduce_none,
  3, 51, :_reduce_none,
  1, 52, :_reduce_none,
  2, 52, :_reduce_none,
  1, 53, :_reduce_none,
  4, 53, :_reduce_none,
  1, 54, :_reduce_none,
  1, 54, :_reduce_none,
  3, 54, :_reduce_none,
  1, 55, :_reduce_none,
  3, 55, :_reduce_none,
  0, 55, :_reduce_none ]

racc_reduce_n = 60

racc_shift_n = 105

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "%" => 4,
  "+" => 5,
  "-" => 6,
  "<" => 7,
  ">" => 8,
  "<=" => 9,
  ">=" => 10,
  "==" => 11,
  "!=" => 12,
  "&" => 13,
  "|" => 14,
  "&&" => 15,
  "||" => 16,
  ")" => 17,
  "}" => 18,
  "(" => 19,
  "{" => 20,
  :RESERVED => 21,
  ";" => 22,
  "," => 23,
  :IDENTIFIER => 24,
  "if" => 25,
  "else" => 26,
  "while" => 27,
  "return" => 28,
  "=" => 29,
  :CONSTANT => 30 }

racc_nt_base = 31

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\"&\"",
  "\"|\"",
  "\"&&\"",
  "\"||\"",
  "\")\"",
  "\"}\"",
  "\"(\"",
  "\"{\"",
  "RESERVED",
  "\";\"",
  "\",\"",
  "IDENTIFIER",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"return\"",
  "\"=\"",
  "CONSTANT",
  "$start",
  "program",
  "external_declaration",
  "declaration",
  "function_definition",
  "declarator_list",
  "declarator",
  "parameter_type_list",
  "compound_statement",
  "parameter_declaration",
  "statement",
  "expression",
  "declaration_list",
  "statement_list",
  "assign_expr",
  "logical_or_expr",
  "logical_and_expr",
  "equality_expr",
  "relational_expr",
  "add_expr",
  "mult_expr",
  "unary_expr",
  "postfix_expr",
  "primary_expr",
  "argument_expression_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class TinyCC
