#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
class TinyCC < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    48,    61,    10,    19,    95,    98,    48,     6,    48,    20,
    53,    99,    60,    51,    23,    18,    29,    62,    40,    51,
    32,    51,    33,    34,    40,    50,    40,    48,     5,    97,
    96,    50,    14,    50,    10,    53,    53,    69,    70,    61,
    51,    23,    48,    29,    23,    40,    24,    32,    48,    33,
    34,    25,    50,    63,    64,    51,    23,    48,    29,    48,
    40,    51,    32,    48,    33,    34,    40,    50,    12,    13,
    51,    10,    51,    50,    48,    40,    51,    74,    48,    54,
    48,    40,    50,    55,    50,    71,    72,    51,    50,    48,
    59,    51,    74,    51,    62,    48,    74,    11,    74,    50,
    71,    72,    51,    50,    10,    50,   103,    74,    51,    48,
    79,    53,     5,    74,    50,    48,   nil,    48,    52,    53,
    50,   nil,    51,    23,    25,    29,    48,    40,    51,    32,
    51,    33,    34,    74,    50,    40,    48,    69,    70,    51,
    50,   nil,    50,   nil,    74,   nil,    48,    69,    70,    51,
   nil,    50,    48,   nil,    40,    69,    70,   nil,    57,    51,
    23,    50,    29,    48,    40,    51,    32,    48,    33,    34,
    74,    50,   nil,    48,    69,    70,    51,    50,    71,    72,
    51,    40,    48,    48,   nil,    74,    51,   nil,    50,    63,
    64,    74,    50,   nil,   nil,    51,    51,   nil,    50,   nil,
    74,    74,    65,    66,    67,    68,   nil,    50,    50,    65,
    66,    67,    68,    65,    66,    67,    68 ]

racc_action_check = [
   103,    40,    13,    16,    75,    82,    55,     1,    99,    16,
    75,    82,    40,   103,   103,    14,   103,    80,   103,    55,
   103,    99,   103,   103,    55,   103,    99,    97,     1,    78,
    77,    55,     9,    99,    18,    78,    77,    90,    90,    74,
    97,    97,    96,    97,    19,    97,    20,    97,    54,    97,
    97,    23,    97,    42,    42,    96,    96,    53,    96,    59,
    96,    54,    96,    51,    96,    96,    54,    96,     8,     8,
    53,    25,    59,    54,    48,    53,    51,    59,    72,    32,
    71,    51,    53,    33,    59,    92,    92,    48,    51,    70,
    39,    72,    48,    71,    41,    69,    72,     6,    71,    48,
    91,    91,    70,    72,     5,    71,   100,    70,    69,    26,
    56,    56,     0,    69,    70,    68,   nil,    61,    30,    30,
    69,   nil,    26,    26,    26,    26,    66,    26,    68,    26,
    61,    26,    26,    68,    26,    61,    34,    89,    89,    66,
    68,   nil,    61,   nil,    66,   nil,    35,    88,    88,    34,
   nil,    66,    65,   nil,    34,    87,    87,   nil,    35,    35,
    35,    34,    35,    60,    35,    65,    35,    64,    35,    35,
    65,    35,   nil,    63,    44,    44,    60,    65,    45,    45,
    64,    60,    62,    67,   nil,    64,    63,   nil,    60,    84,
    84,    63,    64,   nil,   nil,    62,    67,   nil,    63,   nil,
    62,    67,    43,    43,    43,    43,   nil,    62,    67,    85,
    85,    85,    85,    86,    86,    86,    86 ]

racc_action_pointer = [
    91,     7,   nil,   nil,   nil,    80,    97,   nil,    46,    13,
   nil,   nil,   nil,   -22,    -6,   nil,   -14,   nil,    10,    24,
    21,   nil,   nil,    30,   nil,    47,   103,   nil,   nil,   nil,
    96,   nil,    60,    64,   130,   140,   nil,   nil,   nil,    74,
   -18,    79,    42,   195,   169,   176,   nil,   nil,    68,   nil,
   nil,    57,   nil,    51,    42,     0,    88,   nil,   nil,    53,
   157,   111,   176,   167,   161,   146,   120,   177,   109,    89,
    83,    74,    72,   nil,    20,   -13,   nil,    13,    12,   nil,
     2,   nil,   -12,   nil,   178,   202,   206,   150,   142,   132,
    32,    98,    83,   nil,   nil,   nil,    36,    21,   nil,     2,
    79,   nil,   nil,    -6,   nil ]

racc_action_default = [
   -60,   -60,    -1,    -3,    -4,   -60,   -60,    -2,   -60,    -6,
    -8,   105,    -5,   -60,   -12,    -7,   -60,   -10,   -60,   -60,
   -60,   -13,    -9,   -24,   -11,   -60,   -27,   -22,    -6,   -14,
   -60,   -16,   -60,   -60,   -60,   -60,   -23,   -25,   -28,   -30,
   -54,   -32,   -34,   -36,   -39,   -44,   -47,   -50,   -60,   -52,
   -55,   -60,   -15,   -60,   -60,   -60,   -60,   -21,   -26,   -60,
   -60,   -59,   -60,   -60,   -60,   -60,   -60,   -60,   -60,   -60,
   -60,   -60,   -60,   -51,   -54,   -60,   -29,   -60,   -60,   -20,
   -33,   -31,   -60,   -57,   -35,   -37,   -38,   -40,   -41,   -42,
   -43,   -45,   -46,   -48,   -49,   -56,   -60,   -60,   -53,   -60,
   -17,   -19,   -58,   -60,   -18 ]

racc_goto_table = [
    37,    73,    56,    76,    26,    27,    35,     9,    36,    58,
    81,    83,    85,    86,    80,    15,    91,    92,    84,    75,
    21,    17,    77,    78,    93,    94,    22,    28,    87,    88,
    89,    90,     2,     7,    16,     1,    82,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   102,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   100,   101,   nil,   nil,   nil,   nil,   nil,   104 ]

racc_goto_check = [
    10,    21,    11,    14,    12,     3,    13,     6,     3,    10,
    14,    14,    18,    18,    16,     6,    20,    20,    17,    11,
     6,     9,    11,    11,    21,    21,     8,     6,    19,    19,
    19,    19,     2,     2,     7,     1,    24,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    14,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    10,    10,   nil,   nil,   nil,   nil,   nil,    10 ]

racc_goto_pointer = [
   nil,    35,    32,   -18,   nil,   nil,     2,    20,     7,     7,
   -26,   -32,   -19,   -20,   -50,   nil,   -45,   -44,   -51,   -37,
   -53,   -47,   nil,   nil,   -25 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     8,   nil,   nil,    31,   nil,
   nil,    30,   nil,   nil,    38,    39,    41,    42,    43,    44,
    45,    46,    47,    49,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 33, :_reduce_none,
  2, 33, :_reduce_none,
  1, 34, :_reduce_none,
  1, 34, :_reduce_none,
  3, 35, :_reduce_none,
  1, 37, :_reduce_none,
  3, 37, :_reduce_none,
  1, 38, :_reduce_none,
  6, 36, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_none,
  0, 39, :_reduce_none,
  2, 41, :_reduce_none,
  1, 42, :_reduce_none,
  2, 42, :_reduce_none,
  1, 42, :_reduce_none,
  5, 42, :_reduce_none,
  7, 42, :_reduce_none,
  5, 42, :_reduce_none,
  3, 42, :_reduce_none,
  4, 40, :_reduce_none,
  1, 44, :_reduce_none,
  2, 44, :_reduce_none,
  0, 44, :_reduce_none,
  1, 45, :_reduce_none,
  2, 45, :_reduce_none,
  0, 45, :_reduce_none,
  1, 43, :_reduce_none,
  3, 43, :_reduce_none,
  1, 46, :_reduce_none,
  3, 46, :_reduce_none,
  1, 47, :_reduce_none,
  3, 47, :_reduce_none,
  1, 48, :_reduce_none,
  3, 48, :_reduce_none,
  1, 49, :_reduce_none,
  3, 49, :_reduce_none,
  3, 49, :_reduce_none,
  1, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  3, 50, :_reduce_none,
  1, 51, :_reduce_none,
  3, 51, :_reduce_none,
  3, 51, :_reduce_none,
  1, 52, :_reduce_none,
  3, 52, :_reduce_none,
  3, 52, :_reduce_none,
  1, 53, :_reduce_none,
  2, 53, :_reduce_none,
  1, 54, :_reduce_none,
  4, 54, :_reduce_none,
  1, 55, :_reduce_none,
  1, 55, :_reduce_none,
  3, 55, :_reduce_none,
  1, 56, :_reduce_none,
  3, 56, :_reduce_none,
  0, 56, :_reduce_none ]

racc_reduce_n = 60

racc_shift_n = 105

racc_token_table = {
  false => 0,
  :error => 1,
  "*" => 2,
  "/" => 3,
  "%" => 4,
  "+" => 5,
  "-" => 6,
  "<" => 7,
  ">" => 8,
  "<=" => 9,
  ">=" => 10,
  "==" => 11,
  "!=" => 12,
  "&" => 13,
  "|" => 14,
  "&&" => 15,
  "||" => 16,
  ")" => 17,
  "}" => 18,
  "(" => 19,
  "{" => 20,
  :RESERVED => 21,
  ";" => 22,
  "," => 23,
  :IDENTIFIER => 24,
  :parameter_declaraion => 25,
  "if" => 26,
  "else" => 27,
  "while" => 28,
  "return" => 29,
  "=" => 30,
  :CONSTANT => 31 }

racc_nt_base = 32

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"*\"",
  "\"/\"",
  "\"%\"",
  "\"+\"",
  "\"-\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"==\"",
  "\"!=\"",
  "\"&\"",
  "\"|\"",
  "\"&&\"",
  "\"||\"",
  "\")\"",
  "\"}\"",
  "\"(\"",
  "\"{\"",
  "RESERVED",
  "\";\"",
  "\",\"",
  "IDENTIFIER",
  "parameter_declaraion",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"return\"",
  "\"=\"",
  "CONSTANT",
  "$start",
  "program",
  "external_declaration",
  "declaration",
  "function_definition",
  "declarator_list",
  "declarator",
  "parameter_type_list",
  "compound_statement",
  "parameter_declaration",
  "statement",
  "expression",
  "declaration_list",
  "statement_list",
  "assign_expr",
  "logical_or_expr",
  "logical_and_expr",
  "equality_expr",
  "relational_expr",
  "add_expr",
  "mult_expr",
  "unary_expr",
  "postfix_expr",
  "primary_expr",
  "argument_expression_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

# reduce 2 omitted

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

# reduce 16 omitted

# reduce 17 omitted

# reduce 18 omitted

# reduce 19 omitted

# reduce 20 omitted

# reduce 21 omitted

# reduce 22 omitted

# reduce 23 omitted

# reduce 24 omitted

# reduce 25 omitted

# reduce 26 omitted

# reduce 27 omitted

# reduce 28 omitted

# reduce 29 omitted

# reduce 30 omitted

# reduce 31 omitted

# reduce 32 omitted

# reduce 33 omitted

# reduce 34 omitted

# reduce 35 omitted

# reduce 36 omitted

# reduce 37 omitted

# reduce 38 omitted

# reduce 39 omitted

# reduce 40 omitted

# reduce 41 omitted

# reduce 42 omitted

# reduce 43 omitted

# reduce 44 omitted

# reduce 45 omitted

# reduce 46 omitted

# reduce 47 omitted

# reduce 48 omitted

# reduce 49 omitted

# reduce 50 omitted

# reduce 51 omitted

# reduce 52 omitted

# reduce 53 omitted

# reduce 54 omitted

# reduce 55 omitted

# reduce 56 omitted

# reduce 57 omitted

# reduce 58 omitted

# reduce 59 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class TinyCC
