#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.11
# from Racc grammer file "".
#

require 'racc/parser.rb'
class TinyCC < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    60,    54,    24,    54,    32,    64,    43,    35,    77,    36,
    37,    54,     6,    72,    73,    63,    43,    20,    10,    51,
     5,    51,    53,    21,    53,    54,    24,    19,    32,    51,
    43,    35,    53,    36,    37,    54,    54,    24,    65,    32,
    43,    43,    35,    51,    36,    37,    53,    54,    68,    69,
    70,    71,    43,    51,    51,    54,    53,    53,    14,    54,
    77,    54,    66,    67,    43,    51,    77,    54,    53,    54,
    12,    13,    77,    51,    77,    99,    53,    51,    54,    51,
    53,    56,    53,    43,    54,    51,    54,    51,    53,    77,
    53,    77,    54,    24,    28,    32,    51,    43,    35,    53,
    36,    37,    51,    54,    51,    53,   102,    53,    43,    54,
    51,    54,   103,    53,    77,    10,    43,    54,    24,    64,
    32,    51,    43,    35,    53,    36,    37,    51,    54,    51,
    53,   101,    53,    77,    54,    51,    54,    56,    53,    43,
    54,    77,    54,    24,   100,    77,    51,    77,    54,    53,
    56,    19,    51,    77,    51,    53,    28,    53,    51,    10,
    51,    53,    57,    53,    74,    75,    51,    74,    75,    53,
    68,    69,    70,    71,    68,    69,    70,    71,    82,    56,
    55,    56,    72,    73,    72,    73,    72,    73,    72,    73,
    74,    75,    66,    67,    58,    62,    65,    11,    10,   107,
     5 ]

racc_action_check = [
    38,    38,    38,    73,    38,    43,    38,    38,    73,    38,
    38,   103,     1,    94,    94,    43,   103,    17,    13,    38,
     1,    73,    38,    17,    73,   101,   101,    16,   101,   103,
   101,   101,   103,   101,   101,    57,   100,   100,    84,   100,
    57,   100,   100,   101,   100,   100,   101,    56,    46,    46,
    46,    46,    56,    57,   100,    62,    57,   100,     9,    54,
    62,    51,    45,    45,    54,    56,    51,    75,    56,    74,
     8,     8,    75,    62,    74,    78,    62,    54,    58,    51,
    54,    78,    51,    58,    72,    75,    71,    74,    75,    72,
    74,    71,    29,    29,    29,    29,    58,    29,    29,    58,
    29,    29,    72,    64,    71,    72,    86,    71,    64,    69,
    29,    37,    86,    29,    69,    19,    37,   107,   107,    77,
   107,    64,   107,   107,    64,   107,   107,    69,    68,    37,
    69,    81,    37,    68,    63,   107,    67,    81,   107,    63,
    66,    67,    65,    20,    80,    66,    68,    65,    70,    68,
    80,    21,    63,    70,    67,    63,    27,    67,    66,    28,
    65,    66,    35,    65,    96,    96,    70,    95,    95,    70,
    89,    89,    89,    89,    90,    90,    90,    90,    59,    59,
    33,    33,    93,    93,    92,    92,    91,    91,    47,    47,
    48,    48,    88,    88,    36,    42,    44,     6,     5,   104,
     0 ]

racc_action_pointer = [
   192,    12,   nil,   nil,   nil,   187,   197,   nil,    61,    52,
   nil,   nil,   nil,     7,   nil,   nil,    19,    13,   nil,   104,
   136,   143,   nil,   nil,   nil,   nil,   nil,   148,   148,    86,
   nil,   nil,   nil,   171,   nil,   156,   188,   105,    -5,   nil,
   nil,   nil,   192,    -1,   194,    45,    29,   165,   165,   nil,
   nil,    55,   nil,   nil,    53,   nil,    41,    29,    72,   169,
   nil,   nil,    49,   128,    97,   136,   134,   130,   122,   103,
   142,    80,    78,    -3,    63,    61,   nil,   113,    71,   nil,
   140,   127,   nil,   nil,    36,   nil,   102,   nil,   175,   151,
   155,   163,   161,   159,   -10,   142,   139,   nil,   nil,   nil,
    30,    19,   nil,     5,   186,   nil,   nil,   111,   nil ]

racc_action_default = [
   -64,   -64,    -1,    -3,    -4,   -64,   -64,    -2,   -64,    -6,
    -8,   109,    -5,   -64,    -9,    -7,   -14,   -64,   -12,   -64,
   -64,   -64,   -15,   -10,   -23,   -13,   -11,   -28,   -64,   -31,
   -26,    -6,   -16,   -64,   -18,   -64,   -64,   -64,   -64,   -27,
   -29,   -32,   -34,   -58,   -36,   -38,   -40,   -43,   -48,   -51,
   -54,   -64,   -56,   -59,   -64,   -17,   -64,   -64,   -64,   -64,
   -24,   -30,   -64,   -64,   -63,   -64,   -64,   -64,   -64,   -64,
   -64,   -64,   -64,   -64,   -64,   -64,   -55,   -58,   -64,   -33,
   -64,   -64,   -22,   -25,   -37,   -35,   -64,   -61,   -39,   -41,
   -42,   -44,   -45,   -46,   -47,   -49,   -50,   -52,   -53,   -60,
   -64,   -64,   -57,   -64,   -19,   -21,   -62,   -64,   -20 ]

racc_goto_table = [
    40,    76,    59,    79,     9,    30,    29,    39,    18,    61,
    85,    87,    15,    25,    91,    92,    93,    94,    22,    78,
    89,    90,    80,    81,    97,    98,    38,    31,    95,    96,
     2,     7,    27,    83,    26,    84,    88,    16,    23,    17,
     1,    86,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   106,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   104,   105,   nil,   nil,   nil,   nil,   nil,   108 ]

racc_goto_check = [
    12,    25,    13,    18,     6,     3,    14,     3,    11,    12,
    18,    18,     6,    11,    23,    23,    23,    23,     6,    13,
    22,    22,    13,    13,    25,    25,    15,     6,    24,    24,
     2,     2,    16,    17,    10,    20,    21,     9,     8,     7,
     1,    28,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    18,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    12,    12,   nil,   nil,   nil,   nil,   nil,    12 ]

racc_goto_pointer = [
   nil,    40,    30,   -22,   nil,   nil,    -1,    23,    18,    23,
    11,    -8,   -29,   -35,   -21,    -3,     8,   -27,   -53,   nil,
   -27,   -29,   -46,   -54,   -44,   -50,   nil,   nil,   -23 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     8,   nil,   nil,    34,   nil,
   nil,   nil,   nil,    33,   nil,   nil,   nil,   nil,    41,    42,
    44,    45,    46,    47,    48,    49,    50,    52,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 29, :_reduce_1,
  2, 29, :_reduce_2,
  1, 30, :_reduce_3,
  1, 30, :_reduce_4,
  3, 31, :_reduce_5,
  1, 33, :_reduce_6,
  3, 33, :_reduce_7,
  1, 34, :_reduce_8,
  0, 37, :_reduce_9,
  0, 38, :_reduce_10,
  8, 32, :_reduce_11,
  1, 35, :_reduce_12,
  3, 35, :_reduce_13,
  0, 35, :_reduce_none,
  2, 39, :_reduce_15,
  1, 40, :_reduce_16,
  2, 40, :_reduce_17,
  1, 40, :_reduce_18,
  5, 40, :_reduce_19,
  7, 40, :_reduce_20,
  5, 40, :_reduce_21,
  3, 40, :_reduce_22,
  0, 44, :_reduce_23,
  0, 45, :_reduce_24,
  6, 36, :_reduce_25,
  1, 42, :_reduce_26,
  2, 42, :_reduce_27,
  0, 42, :_reduce_none,
  1, 43, :_reduce_29,
  2, 43, :_reduce_30,
  0, 43, :_reduce_none,
  1, 41, :_reduce_32,
  3, 41, :_reduce_33,
  1, 46, :_reduce_34,
  3, 46, :_reduce_35,
  1, 47, :_reduce_36,
  3, 47, :_reduce_37,
  1, 48, :_reduce_38,
  3, 48, :_reduce_39,
  1, 49, :_reduce_40,
  3, 49, :_reduce_41,
  3, 49, :_reduce_42,
  1, 50, :_reduce_43,
  3, 50, :_reduce_44,
  3, 50, :_reduce_45,
  3, 50, :_reduce_46,
  3, 50, :_reduce_47,
  1, 51, :_reduce_48,
  3, 51, :_reduce_49,
  3, 51, :_reduce_50,
  1, 52, :_reduce_51,
  3, 52, :_reduce_52,
  3, 52, :_reduce_53,
  1, 53, :_reduce_54,
  2, 53, :_reduce_55,
  1, 54, :_reduce_56,
  4, 54, :_reduce_57,
  1, 55, :_reduce_58,
  1, 55, :_reduce_59,
  3, 55, :_reduce_60,
  1, 56, :_reduce_61,
  3, 56, :_reduce_62,
  0, 56, :_reduce_none ]

racc_reduce_n = 64

racc_shift_n = 109

racc_token_table = {
  false => 0,
  :error => 1,
  "&&" => 2,
  "||" => 3,
  ")" => 4,
  "}" => 5,
  "(" => 6,
  "{" => 7,
  :RESERVED => 8,
  ";" => 9,
  "," => 10,
  :IDENTIFIER => 11,
  "if" => 12,
  "else" => 13,
  "while" => 14,
  "return" => 15,
  "=" => 16,
  "==" => 17,
  "!=" => 18,
  "<" => 19,
  ">" => 20,
  "<=" => 21,
  ">=" => 22,
  "+" => 23,
  "-" => 24,
  "*" => 25,
  "/" => 26,
  :CONSTANT => 27 }

racc_nt_base = 28

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "\"&&\"",
  "\"||\"",
  "\")\"",
  "\"}\"",
  "\"(\"",
  "\"{\"",
  "RESERVED",
  "\";\"",
  "\",\"",
  "IDENTIFIER",
  "\"if\"",
  "\"else\"",
  "\"while\"",
  "\"return\"",
  "\"=\"",
  "\"==\"",
  "\"!=\"",
  "\"<\"",
  "\">\"",
  "\"<=\"",
  "\">=\"",
  "\"+\"",
  "\"-\"",
  "\"*\"",
  "\"/\"",
  "CONSTANT",
  "$start",
  "program",
  "external_declaration",
  "declaration",
  "function_definition",
  "declarator_list",
  "declarator",
  "parameter_type_list",
  "compound_statement",
  "@1",
  "@2",
  "parameter_declaration",
  "statement",
  "expression",
  "declaration_list",
  "statement_list",
  "@3",
  "@4",
  "assign_expr",
  "logical_or_expr",
  "logical_and_expr",
  "equality_expr",
  "relational_expr",
  "add_expr",
  "mult_expr",
  "unary_expr",
  "postfix_expr",
  "primary_expr",
  "argument_expression_list" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'calc_rule.y', 19)
  def _reduce_1(val, _values, result)
    result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 20)
  def _reduce_2(val, _values, result)
    result =#[val[0],val[1]]}
		                                         val[0]+[val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 23)
  def _reduce_3(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 24)
  def _reduce_4(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 26)
  def _reduce_5(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 29)
  def _reduce_6(val, _values, result)
    #result = [val[0]]}
	                                    result = [make_decl(val[0]).unshift("int")]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 31)
  def _reduce_7(val, _values, result)
    result = val[0].push(make_decl(val[2]).unshift("int"))
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 33)
  def _reduce_8(val, _values, result)
    #result = [val[0]]}
	                      result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 36)
  def _reduce_9(val, _values, result)
    @cur_lev += 1
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 36)
  def _reduce_10(val, _values, result)
    stack_pop
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 38)
  def _reduce_11(val, _values, result)
    	                                                                                      #@cur_lev += 1
	                                                                                       #result = ["func",make_fun_def(val[1],val[4]),val[4],val[6]]
																						   result = ["func",make_fun_def(val[1],val[4])].push(val[4]).push(val[6])
																						   @param_add = 4
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 50)
  def _reduce_12(val, _values, result)
    result = [make_param(val[0])]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 51)
  def _reduce_13(val, _values, result)
    result = val[0].push(make_param(val[2]))
    result
  end
.,.,

# reduce 14 omitted

module_eval(<<'.,.,', 'calc_rule.y', 55)
  def _reduce_15(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 57)
  def _reduce_16(val, _values, result)
    
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 58)
  def _reduce_17(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 59)
  def _reduce_18(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 60)
  def _reduce_19(val, _values, result)
    result = ["IF", val[2],val[4]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 61)
  def _reduce_20(val, _values, result)
    result = ["IF",val[2],val[4],val[6]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 62)
  def _reduce_21(val, _values, result)
    result = ["WHILE",val[2],val[4]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 63)
  def _reduce_22(val, _values, result)
    result = ["RETURN",val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 65)
  def _reduce_23(val, _values, result)
    @cur_lev += 1
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 65)
  def _reduce_24(val, _values, result)
    stack_pop
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 66)
  def _reduce_25(val, _values, result)
    	                                                         #@cur_lev += 1
															 #result = [val[1],val[2]]
															 result = ["comp",val[2],val[3]]
															 #@cur_lev -= 1
															 
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 72)
  def _reduce_26(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 75)
  def _reduce_27(val, _values, result)
    					                              result = val[0]+[val[1]]
    result
  end
.,.,

# reduce 28 omitted

module_eval(<<'.,.,', 'calc_rule.y', 78)
  def _reduce_29(val, _values, result)
    result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 79)
  def _reduce_30(val, _values, result)
    result = val[0] + [val[1]]
    result
  end
.,.,

# reduce 31 omitted

module_eval(<<'.,.,', 'calc_rule.y', 82)
  def _reduce_32(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 83)
  def _reduce_33(val, _values, result)
    result = [val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 85)
  def _reduce_34(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 86)
  def _reduce_35(val, _values, result)
    #result=[val[1],val[0],val[2]]}
			                                result = [val[1],ref_var(val[0]),val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 89)
  def _reduce_36(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 90)
  def _reduce_37(val, _values, result)
    result = [val[1],val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 92)
  def _reduce_38(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 93)
  def _reduce_39(val, _values, result)
    result = [val[1],val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 98)
  def _reduce_40(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 99)
  def _reduce_41(val, _values, result)
    result = [val[1],val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 100)
  def _reduce_42(val, _values, result)
    result = [val[1],val[0],val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 102)
  def _reduce_43(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 103)
  def _reduce_44(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 104)
  def _reduce_45(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 105)
  def _reduce_46(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 106)
  def _reduce_47(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 108)
  def _reduce_48(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 110)
  def _reduce_49(val, _values, result)
    			                         #puts("PLUS!!!")
			                         result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 112)
  def _reduce_50(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 114)
  def _reduce_51(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 115)
  def _reduce_52(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 116)
  def _reduce_53(val, _values, result)
    result = [val[1], val[0], val[2]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 118)
  def _reduce_54(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 119)
  def _reduce_55(val, _values, result)
    result = [val[0], val[1]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 121)
  def _reduce_56(val, _values, result)
    result = val[0]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 122)
  def _reduce_57(val, _values, result)
    #result = ["FCALL", val[0] ,val[2]]}
				                                             result = ref_fun(val[0],val[2].size).push(val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 126)
  def _reduce_58(val, _values, result)
    result = ref_var(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 127)
  def _reduce_59(val, _values, result)
    result = [val[0],"CONSTANT"]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 128)
  def _reduce_60(val, _values, result)
    result = val[1]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 130)
  def _reduce_61(val, _values, result)
    result = [val[0]]
    result
  end
.,.,

module_eval(<<'.,.,', 'calc_rule.y', 131)
  def _reduce_62(val, _values, result)
    result =  val[0]+[val[2]]
    result
  end
.,.,

# reduce 63 omitted

def _reduce_none(val, _values, result)
  val[0]
end

end   # class TinyCC
